---
title: "Project Proposal"
output: github_document
---

# Exploring Patterns in National Park Visitation

## Collaborators:
  •	Miriam Lachs ml5222
  <br /> •	Flora Pang fp2513
  <br /> •	Mari Sanders mos2128
  <br /> •	Lizy Choi jc6452

## Project Motivation:
The project aims to investigate patterns and trends in visitation to national parks across the United States, with the central focus on understanding the various factors of influence such as visitation types, seasonal trends, historical events, and camping activities. As frequent enjoyers of the parks, we hope to investigate what makes the parks popular and understand what tends to drive participation of the public. 

  - Useful for both people to get them into going to the parks 
  - Useful for park services to learn what increases participation 

## Planned Analyses / Intended Final Products:  
  1.	Regional comparison in Visit Type 
    <br />a.	Compare visitation types across different U.S. regions to identify
    visitors’ preferences and trends in popularity

  2.	Seasonal Trends in Park Visitation
    <br />a.	Analyze seasonal fluctuations, identifying peak periods and
    investigating different factors that contribute to the seasonal patterns 

  3.	Historical Events impact 
    <br />a. traffic / carparks, visitor counts, growth of activities offered in
    the park) 
  4.	Trends in activities by park
    <br />a.	Analyze activities by park type and popularity
    
## Planned Visualizations 
  •	Interactive US Map: 
  <br /> &nbsp; &nbsp; a. Develop an interactive map where the size of each
  park’s data point reflects the number of visits 
  <br />•	Plots and visualizations of visitation data, seasonal trends, historical
  data
  <br />•	Modeling activity by entry fee

## Coding Challenges:
  1.	Data Retrieval: 
  <br />a. Working with an API and getting the raw data from
  online into a useable format  
  2.	Data Wrangling: 
    <br />a. cleaning up API documentation and breaking down the data frame for certain parts of the analysis
    <br />b.	Merging Query Builder and API Documentation with correlating
    variables 

## Data Sources:
  1.	[Query Builder for Public Use Statistics](https://irma.nps.gov/Stats/SSRSReports/National%20Reports/Query%20Builder%20for%20Public%20Use%20Statistics%20(1979%20-%20Last%20Calendar%20Year))
  2.	[National Park Service API Documentation](https://www.nps.gov/subjects/developer/api-documentation.htm)

## Timeline:
  Week 0: (Nov. 3 - Nov. 7): Finalize Project Proposal
  <br />Week 1 (Nov. 10 – Nov.16): Data Wrangling + Initial Website Setup
  <br />Week 2 (Nov.17 – Nov. 23): Data Visualization + Final Report Writeup 
  <br />Week 3 (Nov. 24 – Nov. 30): Editing + Organizing Website + Touchups 
  <br />Week 4(Dec. 1 – Dec 7): Video Recording + Editing
