---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(httr)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(leaflet)
```

```{r, include=FALSE}
res=GET('https://developer.nps.gov/api/v1/parks?limit=500&api_key=B9nDpbkbrb3kSOjz6kXSxMJ3d6MSpUvt1QqYdeyn')

data = res %>% content("text") %>% jsonlite::fromJSON() %>% as_tibble()

NPS_data_parks=data %>% unnest(data) %>% select(fullName,parkCode,description,latitude,longitude,activities,states,entranceFees,operatingHours,designation) %>% unnest(activities,names_sep = '_') %>% unnest(entranceFees,names_sep = '_') %>% unnest(operatingHours,names_sep = '_') 

NPS_data_visits=read_csv('Query Builder for Public Use Statistics (1979 - Last Calendar Year).csv')

NPS_Full=NPS_data_parks %>%   mutate(entranceFees_cost=as.numeric(entranceFees_cost)) %>% 
mutate(parkCode=str_to_upper(parkCode))%>% full_join(NPS_data_visits,by=join_by('parkCode'=='UnitCode'))
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}

activities_choices = NPS_Full %>% select(activities_name) %>% drop_na()%>% distinct %>% arrange(activities_name) %>%  pull(activities_name)
selectInput(
  inputId = "act_choice",
  label = h3("Select Activity"),
  choices = activities_choices)
```


```{r}
radioButtons(
  inputId = 'fee_choice',
  label=h3("Do Fees Apply"),
  choices = c(TRUE,FALSE)
)
```


```{r}
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderLeaflet(
  
NPS_Full %>% mutate(latitude=as.numeric(latitude),longitude=as.numeric(longitude)) %>%
  filter(activities_name==input[['act_choice']]) %>% 
  select(fullName,latitude,longitude) %>% distinct() %>% leaflet() %>% addTiles() %>% addMarkers(~longitude,~latitude,label = ~fullName)
)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint({ 
  input[["type_choice"]]
})
```

### Chart C

```{r}

```

